min_score: 70
max_cves: 1
disallow:
  - "MISSING_PIN"
  - "UNVERIFIED_SOURCE"
  - "[KNOWN_VULN]"
min_trust_score: 70
publisher_expectations:
  torch: "pypi"
  transformers: "pypi"
exceptions:
  - code: "UNKNOWN_LICENSE"
    subject: "internal-model"
    reason: "Internal model license tracked out-of-band"
    approved_by: "security-review"
    expires: "2025-12-31T23:59:59"
  - code: "STALE_MODEL"
    subject: "demo-embedding"
    reason: "Benchmarks rely on this snapshot for regression tests"
    approved_by: "ml-lead"
